<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="15" passed="0" failed="0" skipped="15">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-27T22:47:54 GMT" name="flight-reservation" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11311">
    <groups>
    </groups>
    <test started-at="2024-04-27T22:47:54 GMT" name="passengers-count-3" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11278">
      <class name="com.vikasdocker.flightreservationtest.FlightReservationTest">
        <test-method is-config="true" signature="setupConfig()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:47:53 GMT" name="setupConfig" finished-at="2024-04-27T22:47:53 GMT" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupConfig -->
        <test-method is-config="true" signature="setDriver(org.testng.ITestContext)[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:47:54 GMT" name="setDriver" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11245" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@514115c7]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
at com.vikasdocker.AbstractTest.getRemoteDriver(AbstractTest.java:63)
at com.vikasdocker.AbstractTest.setDriver(AbstractTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.beforeRun(TestRunner.java:650)
at org.testng.TestRunner.run(TestRunner.java:612)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.6.22-linuxkit', java.version: '22.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:392)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
... 21 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
... 3 more
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
... 10 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method is-config="true" signature="setParameters(java.lang.String)[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="setParameters" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.AbstractTest.setDriver" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setParameters -->
        <test-method signature="userRegistrationTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="userRegistrationTest" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
at com.vikasdocker.AbstractTest.getRemoteDriver(AbstractTest.java:63)
at com.vikasdocker.AbstractTest.setDriver(AbstractTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.beforeRun(TestRunner.java:650)
at org.testng.TestRunner.run(TestRunner.java:612)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.6.22-linuxkit', java.version: '22.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:392)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
... 21 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
... 3 more
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
... 10 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userRegistrationTest -->
        <test-method is-config="true" signature="sleep()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="sleep" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sleep -->
        <test-method signature="flightSelectionTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="flightSelectionTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSelectionTest -->
        <test-method signature="flightSearchTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="flightSearchTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
        <test-method signature="flightReservationConfirmationTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="flightReservationConfirmationTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightReservationConfirmationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightReservationConfirmationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightReservationConfirmationTest -->
        <test-method signature="registrationConfirmationTEST()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="registrationConfirmationTEST" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationConfirmationTEST -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@742ff096]" started-at="2024-04-27T22:48:05 GMT" name="quitBrowser" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.vikasdocker.flightreservationtest.FlightReservationTest -->
    </test> <!-- passengers-count-3 -->
    <test started-at="2024-04-27T22:47:54 GMT" name="passengers-count-2" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11311">
      <class name="com.vikasdocker.flightreservationtest.FlightReservationTest">
        <test-method is-config="true" signature="setDriver(org.testng.ITestContext)[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:47:54 GMT" name="setDriver" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11239" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@200164c8]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
at com.vikasdocker.AbstractTest.getRemoteDriver(AbstractTest.java:63)
at com.vikasdocker.AbstractTest.setDriver(AbstractTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.beforeRun(TestRunner.java:650)
at org.testng.TestRunner.run(TestRunner.java:612)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.6.22-linuxkit', java.version: '22.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:392)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
... 21 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
... 3 more
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
... 10 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method is-config="true" signature="setParameters(java.lang.String)[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="setParameters" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.AbstractTest.setDriver" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setParameters -->
        <test-method signature="userRegistrationTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="userRegistrationTest" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
at com.vikasdocker.AbstractTest.getRemoteDriver(AbstractTest.java:63)
at com.vikasdocker.AbstractTest.setDriver(AbstractTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.beforeRun(TestRunner.java:650)
at org.testng.TestRunner.run(TestRunner.java:612)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.6.22-linuxkit', java.version: '22.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:392)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
... 21 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
... 3 more
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
... 10 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userRegistrationTest -->
        <test-method is-config="true" signature="sleep()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="sleep" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sleep -->
        <test-method signature="registrationConfirmationTEST()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="registrationConfirmationTEST" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest" duration-ms="10" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationConfirmationTEST -->
        <test-method signature="flightSearchTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="flightSearchTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
        <test-method signature="flightSelectionTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="flightSelectionTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSelectionTest -->
        <test-method signature="flightReservationConfirmationTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="flightReservationConfirmationTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightReservationConfirmationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightReservationConfirmationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightReservationConfirmationTest -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@712625fd]" started-at="2024-04-27T22:48:05 GMT" name="quitBrowser" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.vikasdocker.flightreservationtest.FlightReservationTest -->
    </test> <!-- passengers-count-2 -->
    <test started-at="2024-04-27T22:47:54 GMT" name="passenger-1" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11272">
      <class name="com.vikasdocker.flightreservationtest.FlightReservationTest">
        <test-method is-config="true" signature="setDriver(org.testng.ITestContext)[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:47:54 GMT" name="setDriver" finished-at="2024-04-27T22:48:05 GMT" duration-ms="11243" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@14b8ba06]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
at com.vikasdocker.AbstractTest.getRemoteDriver(AbstractTest.java:63)
at com.vikasdocker.AbstractTest.setDriver(AbstractTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.beforeRun(TestRunner.java:650)
at org.testng.TestRunner.run(TestRunner.java:612)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.6.22-linuxkit', java.version: '22.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:392)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
... 21 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
... 3 more
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
... 10 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method is-config="true" signature="setParameters(java.lang.String)[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="setParameters" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.AbstractTest.setDriver" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setParameters -->
        <test-method signature="userRegistrationTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="userRegistrationTest" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '00ecd0d010eb', ip: '172.26.0.5'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
at com.vikasdocker.AbstractTest.getRemoteDriver(AbstractTest.java:63)
at com.vikasdocker.AbstractTest.setDriver(AbstractTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.beforeRun(TestRunner.java:650)
at org.testng.TestRunner.run(TestRunner.java:612)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.6.22-linuxkit', java.version: '22.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:392)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
... 21 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
... 3 more
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
... 10 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userRegistrationTest -->
        <test-method is-config="true" signature="sleep()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="sleep" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sleep -->
        <test-method signature="registrationConfirmationTEST()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="registrationConfirmationTEST" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.userRegistrationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationConfirmationTEST -->
        <test-method signature="flightSearchTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="flightSearchTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.registrationConfirmationTEST() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
        <test-method signature="flightSelectionTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="flightSelectionTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSearchTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSelectionTest -->
        <test-method signature="flightReservationConfirmationTest()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="flightReservationConfirmationTest" finished-at="2024-04-27T22:48:05 GMT" depends-on-methods="com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightReservationConfirmationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.vikasdocker.flightreservationtest.FlightReservationTest.flightReservationConfirmationTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8 depends on not successfully finished methods 
[com.vikasdocker.flightreservationtest.FlightReservationTest.flightSelectionTest() on instance com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightReservationConfirmationTest -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.vikasdocker.flightreservationtest.FlightReservationTest@4145bad8]" started-at="2024-04-27T22:48:05 GMT" name="quitBrowser" finished-at="2024-04-27T22:48:05 GMT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.vikasdocker.flightreservationtest.FlightReservationTest -->
    </test> <!-- passenger-1 -->
  </suite> <!-- flight-reservation -->
</testng-results>
